# Generated by Django 3.1.4 on 2020-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=200)),
                ('lastName', models.CharField(default='', max_length=200)),
                ('startTime', models.DateTimeField(default='')),
                ('endTime', models.DateTimeField(default='')),
                ('seats', models.SmallIntegerField(default=1)),
                ('accept', models.BooleanField(default=False)),
                ('deny', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
